FROM eclipse-temurin:17-jdk-jammy AS build
WORKDIR /workspace

COPY . .

RUN chmod +x ./gradlew

RUN ./gradlew build --no-daemon

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

COPY --from=build /workspace/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
